import { ArrowRight, ShieldCheck, Network, FileText, Search, Lock, CheckCircle2 } from "lucide-react";
export default function Landing({onStart,onLogin}:{onStart:()=>void;onLogin:()=>void}) {
 return <div className="min-h-screen bg-bg text-ink">
  <header className="h-[76px] px-6 md:px-12 flex items-center justify-between border-b border-border/60 bg-card/70">
   <button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="text-left"><div className="font-display text-[28px] tracking-[.18em]">LINEAGE</div><p className="text-[9px] tracking-[.16em] text-muted">TRACE TRUTH. PROTECT PEOPLE.</p></button>
   <nav className="hidden md:flex items-center gap-8 text-[12.5px] text-muted"><a href="#product">Product</a><a href="#how">How It Works</a><a href="#capabilities">Capabilities</a><a href="#about">About</a></nav>
   <div className="flex items-center gap-2"><button onClick={onLogin} className="hidden sm:block rounded-xl border border-brand px-4 py-2.5 text-[12px] font-semibold text-brand">Log in</button><button onClick={onStart} className="rounded-xl bg-brand text-white px-5 py-2.5 text-[12px] font-semibold">Get Started <ArrowRight size={14} className="inline ml-1"/></button></div>
  </header>
  <section className="max-w-[1320px] mx-auto px-6 md:px-12 pt-16 pb-14 grid lg:grid-cols-[.9fr_1.1fr] gap-12 items-center">
   <div><div className="inline-flex rounded-full bg-soft px-4 py-2 text-[11px] font-semibold tracking-wide text-brand">AI-POWERED INVESTIGATION PLATFORM</div><h1 className="font-display text-[52px] md:text-[68px] leading-[.98] tracking-[-.04em] mt-6 max-w-2xl">Don't just detect the deepfake.<br/><span className="text-brand">Trace the attack.</span></h1><p className="text-[16px] text-muted leading-relaxed mt-6 max-w-xl">LINEAGE helps you detect manipulated media, trace its origin, and build evidence backed by AI — so you can understand the truth and take action.</p><div className="flex flex-wrap gap-3 mt-8"><button onClick={onStart} className="rounded-xl bg-brand text-white px-6 py-3.5 text-[13px] font-semibold">Get Started <ArrowRight size={15} className="inline ml-1"/></button><button onClick={()=>document.getElementById("how")?.scrollIntoView({behavior:"smooth"})} className="rounded-xl border border-border bg-card px-6 py-3.5 text-[13px] font-semibold">Watch Demo <span className="ml-2 text-muted">2 min</span></button></div><div className="grid sm:grid-cols-3 gap-5 mt-10">{[[ShieldCheck,"Detect","AI-manipulated media"],[Network,"Trace","Content propagation"],[FileText,"Build Evidence","Actionable evidence"]].map(([I,t,d]:any)=><div key={t} className="flex gap-3"><div className="h-9 w-9 rounded-xl bg-soft text-brand flex items-center justify-center"><I size={18}/></div><div><p className="text-[12px] font-semibold">{t}</p><p className="text-[10.5px] text-muted mt-1">{d}</p></div></div>)}</div></div>
   <div className="relative"><div className="rounded-[28px] bg-brandDark p-4 md:p-6 shadow-[0_30px_70px_rgba(38,55,42,.2)]"><div className="bg-[#F8F9F6] rounded-2xl p-5"><div className="flex items-center justify-between border-b border-border pb-4"><span className="font-display tracking-[.12em]">LINEAGE</span><span className="rounded-full bg-amber px-3 py-1 text-[10px] text-[#78571A]">Evidence Building</span></div><div className="grid grid-cols-2 gap-4 mt-5"><div className="h-44 rounded-xl bg-soft flex flex-col items-center justify-center"><ShieldCheck size={38} className="text-brand"/><b className="text-3xl mt-3">87%</b><span className="text-[10px] text-muted">Likely manipulated</span></div><div className="rounded-xl border border-border p-4"><p className="text-[12px] font-semibold">Source Tracing</p><div className="h-32 mt-3 relative"><div className="absolute left-4 top-5 h-3 w-3 rounded-full bg-brand"/><div className="absolute left-1/2 top-12 h-3 w-3 rounded-full bg-brand"/><div className="absolute right-5 top-4 h-3 w-3 rounded-full bg-brand"/><div className="absolute left-1/4 bottom-3 h-3 w-3 rounded-full bg-brand"/><svg className="absolute inset-0 w-full h-full"><path d="M18 28 Q80 55 145 22 M18 28 Q45 85 70 120 M145 22 Q110 70 82 120" fill="none" stroke="#91A19A" strokeWidth="2"/></svg></div><p className="text-[10.5px] text-muted">4 source relationships preserved</p></div></div><div className="grid grid-cols-3 gap-3 mt-4"><Mini title="Fingerprint" value="96% match"/><Mini title="Propagation" value="5 sources"/><Mini title="Report" value="Ready"/></div></div></div></div>
  </section>
  <section id="product" className="border-y border-border bg-card py-14"><div className="max-w-[1150px] mx-auto px-6"><p className="text-center text-[10px] tracking-[.2em] uppercase text-muted">Built for evidence-led digital safety</p><div className="grid md:grid-cols-3 gap-5 mt-9">{[[Search,"Detect manipulation","Receive a likelihood score with a plain-language explanation instead of a simplistic fake/real label."],[FingerprintIcon,"Fingerprint content","Generate signatures for visual, audio, face and key-frame matching."],[Lock,"Preserve the trail","Organize sources, timestamps, screenshots and analysis in one evidence locker."]].map(([I,t,d]:any)=><div className="rounded-2xl border border-border p-6" key={t}><I className="text-brand"/><h3 className="font-display text-[23px] mt-5">{t}</h3><p className="text-[13px] text-muted leading-relaxed mt-2">{d}</p></div>)}</div></div></section>
  <section id="how" className="max-w-[1150px] mx-auto px-6 py-16"><div className="flex justify-between gap-8 items-end"><div><p className="text-[11px] uppercase tracking-[.16em] text-brand font-semibold">How it works</p><h2 className="font-display text-[42px] leading-tight mt-2">From detection to action — in four steps.</h2></div></div><div className="grid md:grid-cols-4 gap-4 mt-10">{[["01","Upload","Add a video, image, or source link."],["02","Analyze","Assess manipulation and generate fingerprints."],["03","Trace","Visualize how the content appears across sources."],["04","Act","Understand the gaps and generate a report."]].map(([n,t,d])=><div key={n} className="rounded-2xl border border-border p-5"><span className="text-[11px] font-mono text-brand">{n}</span><h3 className="text-[16px] font-semibold mt-5">{t}</h3><p className="text-[12px] text-muted leading-relaxed mt-2">{d}</p></div>)}</div></section>
  <section id="about" className="bg-brandDark text-white py-16"><div className="max-w-[1000px] mx-auto px-6 text-center"><p className="text-[10px] tracking-[.18em] uppercase text-white/50">A responsible investigation platform</p><h2 className="font-display text-[42px] mt-3">Context matters as much as detection.</h2><p className="text-[14px] text-white/70 max-w-2xl mx-auto mt-4 leading-relaxed">LINEAGE distinguishes what available evidence establishes from what remains unresolved. It provides investigative leads, not accusations or definitive identity claims.</p><button onClick={onStart} className="mt-7 rounded-xl bg-white text-brand px-6 py-3 text-[13px] font-semibold">Start an Investigation <ArrowRight size={15} className="inline ml-1"/></button></div></section>
  <footer className="px-6 md:px-12 py-8 bg-card border-t border-border flex flex-col md:flex-row gap-3 justify-between text-[11px] text-muted"><span>LINEAGE · Trace Truth. Protect People.</span><span>Privacy · Terms · Safety · Resources</span></footer>
 </div>
}
function Mini({title,value}:{title:string;value:string}){return <div className="rounded-xl border border-border p-3"><p className="text-[9px] text-muted">{title}</p><p className="text-[12px] font-semibold mt-2">{value}</p></div>}
function FingerprintIcon({className}:{className?:string}){return <svg className={className} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M12 11a3 3 0 0 1 3 3v1"/><path d="M9 14a3 3 0 0 1 6 0v3"/><path d="M6 13a6 6 0 0 1 12 0v2"/><path d="M4 13a8 8 0 0 1 16 0v1"/><path d="M8 18v-3a4 4 0 0 1 8 0v3"/><path d="M12 5a8 8 0 0 1 8 8"/></svg>}
