"""
Central app configuration. Everything here is overridable via a .env file
(see .env.example) or real environment variables — nothing is hardcoded so
this runs unchanged in local dev, Docker, or a real deployment.
"""
from functools import lru_cache
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    # --- App ---
    APP_NAME: str = "LINEAGE API"
    ENV: str = "development"
    DEBUG: bool = True

    # --- Database ---
    # Defaults to a local SQLite file so `uvicorn app.main:app` works with zero
    # setup. Per the TRD, SQLite is an accepted stand-in for Postgres during
    # early development — set DATABASE_URL to a real Postgres DSN
    # (postgresql+psycopg2://user:pass@host:5432/lineage) for anything beyond
    # a single developer's machine.
    DATABASE_URL: str = "sqlite:///./data/lineage.db"

    # --- Auth ---
    # Generate a real secret for anything beyond local dev:
    #   python -c "import secrets; print(secrets.token_hex(32))"
    JWT_SECRET_KEY: str = "dev-only-secret-change-me"
    JWT_ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24  # 24h — fine for a demo, shorten for production

    # Load the ML models when the server starts instead of on the first
    # request. Costs a few seconds of startup time but avoids a slow (and
    # previously contended) first upload. Set false for fast dev restarts.
    PRELOAD_MODELS: bool = True

    # --- LLM report generation (optional) ---
    # If set, the Incident Report's summary paragraph is generated by a real
    # LLM call using the structured evidence as input (TRD §5.4). If left
    # blank, a deterministic template (app/services/report_builder.py)
    # produces the summary instead — the report's JSON *schema* is identical
    # either way; only the summary's prose source changes.
    ANTHROPIC_API_KEY: str = ""
    ANTHROPIC_MODEL: str = "claude-sonnet-4-5"

    # --- Image-led public web discovery (optional) ---
    GEMINI_API_KEY: str = ""
    GEMINI_SEARCH_MODEL: str = "gemini-3.8-flash"
    MAX_WEB_SEARCHES_PER_MEDIA: int = 3

    # --- Phase 3A: Neo4j graph persistence (optional) ---
    # Leave NEO4J_URI blank to run without Neo4j: every graph endpoint then
    # serves the in-memory KnowledgeGraph (the Phase 3A behaviour). These are
    # backend-only settings and are never sent to the frontend.
    NEO4J_URI: str = ""                  # e.g. bolt://localhost:7687 (neo4j:// for clusters)
    NEO4J_USER: str = "neo4j"
    NEO4J_PASSWORD: str = ""
    NEO4J_DATABASE: str = "neo4j"
    NEO4J_CONNECT_TIMEOUT: float = 3.0   # seconds; keeps the fallback fast when Neo4j is down
    NEO4J_RETRY_SECONDS: float = 30.0    # after a failed connection, wait this long before retrying
    # When true, reading an investigation's graph first re-syncs it (idempotent MERGE) so Neo4j
    # never serves a stale view of the SQL records. Set false to only sync via the sync endpoint/CLI.
    NEO4J_AUTO_SYNC: bool = True

    # --- Phase 3B: Investigation Copilot (Graph RAG) ---
    # "anthropic" uses ANTHROPIC_API_KEY; "none" disables the LLM. With no LLM (or no key) the
    # Copilot still answers from the retrieved graph/evidence using a deterministic composer.
    COPILOT_LLM_PROVIDER: str = "anthropic"
    COPILOT_MODEL: str = "claude-opus-5-5"
    COPILOT_MAX_TOKENS: int = 4000

    # --- Phase 4: ML Intelligence (local, deterministic; all thresholds explainable) ---
    ML_SIMILARITY_THRESHOLD: float = 0.75       # min perceptual-hash similarity (0-1) to report a pair
    ML_CLUSTER_THRESHOLD: float = 0.85          # single-linkage edge threshold for clustering
    ML_ANOMALY_MIN_OBSERVATIONS: int = 4        # timed observations needed to establish a baseline interval
    ML_ANOMALY_MIN_RELATIONSHIPS: int = 3       # timed relationships needed for a propagation-timing baseline
    ML_BURST_RATIO: float = 0.25                # interval < ratio x median interval counts as unusually fast
    ML_GEO_SPREAD_KM: float = 500.0             # max distance between >=3 locations inside one normal interval

    # --- File storage ---
    DATA_DIR: str = "./data"
    UPLOADS_DIR: str = "./data/uploads"
    MAX_UPLOAD_MB: int = 500

    # Symmetric key used to encrypt uploaded files at rest (Fernet/AES-128).
    # Generate a real one with:
    #   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    # If left as the placeholder, the app will generate and persist one on
    # first run (dev convenience) — but a real deployment must set this
    # explicitly so restarts don't orphan already-encrypted files.
    FILE_ENCRYPTION_KEY: str = ""

    # --- CORS ---
    # The Vite dev server's default origin. Add your deployed frontend's
    # origin here (comma-separated) once you have one.
    CORS_ORIGINS: str = "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174"

    @property
    def cors_origins_list(self) -> list[str]:
        return [o.strip() for o in self.CORS_ORIGINS.split(",") if o.strip()]


@lru_cache
def get_settings() -> Settings:
    return Settings()
